"""updating models

Revision ID: 0e03f57cd47e
Revises: 512897ab0419
Create Date: 2023-09-11 15:19:11.177375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e03f57cd47e'
down_revision = '512897ab0419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_categories')
    op.drop_table('sales_stores')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sales_store_id_stores'), 'stores', ['store_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_category_id_categories'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_category_id_categories'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_store_id_stores'), type_='foreignkey')
        batch_op.drop_column('store_id')
        batch_op.drop_column('category_id')

    op.create_table('sales_stores',
    sa.Column('sales_id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name='fk_sales_stores_sales_id_sales'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_sales_stores_store_id_stores'),
    sa.PrimaryKeyConstraint('sales_id', 'store_id', name='pk_sales_stores')
    )
    op.create_table('sales_categories',
    sa.Column('sales_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_sales_categories_category_id_categories'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name='fk_sales_categories_sales_id_sales'),
    sa.PrimaryKeyConstraint('sales_id', 'category_id', name='pk_sales_categories')
    )
    # ### end Alembic commands ###
