"""added sales associations

Revision ID: 512897ab0419
Revises: c18c0cf84139
Create Date: 2023-09-11 12:02:25.203528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512897ab0419'
down_revision = 'c18c0cf84139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_categories',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_sales_categories_category_id_categories')),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name=op.f('fk_sales_categories_sales_id_sales')),
    sa.PrimaryKeyConstraint('sales_id', 'category_id', name=op.f('pk_sales_categories'))
    )
    op.create_table('sales_stores',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name=op.f('fk_sales_stores_sales_id_sales')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_stores_store_id_stores')),
    sa.PrimaryKeyConstraint('sales_id', 'store_id', name=op.f('pk_sales_stores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_stores')
    op.drop_table('sales_categories')
    # ### end Alembic commands ###
