"""updated models

Revision ID: a1a1aa88dfbb
Revises: 1bdf01c3b7cd
Create Date: 2023-09-07 14:52:48.246700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a1aa88dfbb'
down_revision = '1bdf01c3b7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_status')

    op.drop_table('products')
    op.drop_table('user_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_approved_user')

    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('timeframes')
    op.drop_table('categories')
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.Column('sale_amount', sa.FLOAT(), nullable=False),
    sa.Column('sale_units', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_sales_category_id_categories'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_sales_store_id_stores'),
    sa.PrimaryKeyConstraint('id', name='pk_sales')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_categories_product_id_products'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_categories_store_id_stores'),
    sa.PrimaryKeyConstraint('id', name='pk_categories'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_table('timeframes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sales_amount', sa.FLOAT(), nullable=False),
    sa.Column('sales_units', sa.INTEGER(), nullable=False),
    sa.Column('usersession_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_timeframes')
    )
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=255), nullable=False),
    sa.Column('market', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_stores_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_stores'),
    sa.UniqueConstraint('name', name='uq_stores_name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('approved_user', sa.BOOLEAN(), nullable=True),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_approved_user', ['approved_user'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login_time', sa.VARCHAR(), nullable=False),
    sa.Column('logout_time', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user_sessions'),
    sa.UniqueConstraint('session_token', name='uq_user_sessions_session_token')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sku', sa.INTEGER(), nullable=True),
    sa.Column('detail', sa.VARCHAR(length=500), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_products_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_products')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_status', ['status'], unique=False)

    # ### end Alembic commands ###
