"""added relations

Revision ID: c18c0cf84139
Revises: 14e9488461e3
Create Date: 2023-09-11 11:58:36.874150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18c0cf84139'
down_revision = '14e9488461e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_category_id_categories'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeframemodel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sales_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_timeframemodel_id_timeframes'), 'timeframes', ['timeframemodel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_timeframemodel_id_timeframes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_user_id_users'), type_='foreignkey')
        batch_op.drop_column('timeframemodel_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
